### ISSUE TITLE
Dispather Map issue

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#40]
In map if I select Busy checkbox I see all who are in reservation and off from application.
We need to see only those who are in reservation (red in a queue)

We had this issue before and I thought it is fixed

![map](https://cloud.githubusercontent.com/assets/592627/10942492/0e8a5a7a-8319-11e5-8624-74aa22e49a94.jpg)

**Comment by agilecubeteam** [comment]
@Aram4ik 
I am really surprised then how come #24 is updated to close status?

**Comment by Aram4ik** [comment]
Sometimes when issue is trivial (not so important and easy to fix) and you mark it fixed I just trust you and don't make my test. You know it's what I want the most from you - understanding. That I make a ticket, we talk by skype, explain once again and when I see that it is fixed, then it's fixed. Testing of this issue takes less than a minute and there is no hidden scenarios. I am 100% sure that you haven't made testing and this is a real problem for future bigger projects. 

And now you tell me that you are wondered how I marked this issue closed. My answer is - I am wondered that you makred this issue fixed.

**Comment by agilecube** [comment]
@agilecubeteam / @Aram4ik : That was my mistake in explaining to team. I am sorry. Guys please fix it.

**Comment by agilecubeteam** [comment]
I think we are again miss-understanding. (That's what my team did in #24)

Rajul - Busy => Status = Busy. that include people who have logged in but no reservation and people with reservation. And Aram is asking to show taxi with only Reservation not just busy.

Aram, 
Let me put it in this way.
1. Map, was filtered based on status. (as per initial requirement)
2. You asked us to change based on queue Status (For Busy)
3. My team understood that we need to show only two status filter
4. My team has developed and fixed it
5. You tested and marked it closed

So, I am trying to say that we need your one shot cross check before you close any issue. which you missed in this case. Does that mean my team has not done testing?

It is understood in different way and that's why we have closed status so that you can cross check what has been done before we move that issue from list.

I strongly recommend to check issue before you move it to close. There might be chance of difference in understanding.

**Comment by Aram4ik** [comment]
Rajul, please read #24 again.

"Busy shows only those who are available but as reservation (red in queue)". I can't me more accurate. I don't the point of our several hour calls where you clarify everything once again but still there is miss-understanding.

I will check all before closing next time, but still, I guess this is too trivial to make testing on my side
